name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Collect dependencies
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: Build
      run: make
    - name: Upload atropine
      uses: actions/upload-artifact@v2
      with:
        name: atropine
        path: targets/payload/atropine
    - name: Upload atropine hooker
      uses: actions/upload-artifact@v2
      with:
        name: hooker
        path: targets/hooker/hooker
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set build version
      run: |
         echo "::set-env name=BUILD_VERSION::$(echo "$(git log -1 --pretty=format:'%H' | cut -c1-8  | tr -d '\n')")"
         echo "::set-env name=COMMIT_MSG::$(echo "$(git log -1 --pretty=%B)")"
    - name: Download atropine
      uses: actions/download-artifact@v1
      with:
        name: atropine
        path: atropine
    - name: Download atropine hooker
      uses: actions/download-artifact@v1
      with:
        name: hooker
        path: hooker
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.BUILD_VERSION }}
        release_name: Build ${{ env.COMMIT_MSG }}
        draft: false
        prerelease: false
    - name: Upload atropine
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'atropine'
        releaseId: ${{ env.BUILD_VERSION }}
    - name: Upload atropine hooker
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'hooker'
        releaseId: ${{ env.BUILD_VERSION }}