name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Collect dependencies
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: Build
      run: make
    - name: Upload atropine
      uses: actions/upload-artifact@v2
      with:
        name: atropine
        path: targets/payload/atropine
    - name: Upload atropine hooker
      uses: actions/upload-artifact@v2
      with:
        name: hooker
        path: targets/hooker/hooker
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set build version
      run: |
         echo "::set-env name=BUILD_VERSION::$(echo "$(git log -1 --pretty=format:'%H' | cut -c1-8  | tr -d '\n')")"
         echo "::set-env name=COMMIT_MSG::$(echo "$(git log -1 --pretty=%B)")"
    - name: Download atropine
      uses: actions/download-artifact@v1
      with:
        name: atropine
        path: atropine-payload
    - name: Download atropine hooker
      uses: actions/download-artifact@v1
      with:
        name: hooker
        path: hooker-payload
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.BUILD_VERSION }}
        release_name: Build ${{ env.COMMIT_MSG }}
        draft: false
        prerelease: false
    - name: Upload atropine
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: atropine-payload
        asset_name: atropine
        asset_content_type: application/octet-stream
    - name: Upload atropine hooker
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: hooker-payload
        asset_name: hooker
        asset_content_type: application/octet-stream
