name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Collect dependencies
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: Build
      run: make
    - name: Upload atropine
      uses: actions/upload-artifact@v2
      with:
        name: atropine
        path: targets/payload/atropine
    - name: Upload atropine hooker
      uses: actions/upload-artifact@v2
      with:
        name: hooker
        path: targets/hooker/hooker
    - name: set build version
      run: |
          echo "::set-env name=BUILD_VERSION::$(echo "$(git log -1 --pretty=format:'%H' | cut -c1-8  | tr -d '\n')")"
          echo "::set-env name=COMMIT_MSG::$(echo "$(git log -1 --pretty=%B)")"
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.BUILD_VERSION }}
        prerelease: false
        title: ${{ env.COMMIT_MSG }}
        files: |
          targets/hooker/hooker
          targets/payload/atropine