name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Collect dependencies
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: Build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: atropine
        path: targets/payload/atropine
    - uses: actions/upload-artifact@v2
      with:
        name: hooker
        path: targets/hooker/hooker
    - name: Add to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*'